# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['app.py'],
    pathex=['..\\..\\..\\virtualenvs\\QuickDraw\\Lib\\site-packages', 'model\\api\\api.py',
    'model\\api\\client.py',
    'model\\api\\ms_graph\\client.py',
    'model\\api\\ms_graph\\drive_items.py',
    'model\\api\\ms_graph\\drives.py',
    'model\\api\\ms_graph\\groups.py',
    'model\\api\\ms_graph\\mail.py',
    'model\\api\\ms_graph\\notes.py',
    'model\\api\\ms_graph\\personal_contacts.py',
    'model\\api\\ms_graph\\search.py',
    'model\\api\\ms_graph\\session.py',
    'model\\api\\ms_graph\\users.py',
    'model\\api\\ms_graph\\utils\\range.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\application.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\comments.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\enums.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\range.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\table.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\workbook.py',
    'model\\api\\ms_graph\\workbooks_and_charts\\worksheets.py',
    'model\\base_model.py',
    'model\\config.py',
    'model\\dir_handler.py',
    'model\\dir_watcher.py',
    'model\\email.py',
    'model\\pdf.py',
    'presenter\\presenter.py',
    'view\\base_view.py',
    'view\\dialogs.py',
    'view\\sys_tray_icon.py',
    '.',
    ],
    binaries=[],
    datas=[
        ('resources\\configurations.ini', '.'), 
        ('resources\\icon.ico', '.'),
        ('README.md', '.'),
        ('README.html', '.'),
        ('LICENSE.txt', '.')],
    hiddenimports=[],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='one_file',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
